apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- ../common/cert-manager/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
# Istio
# - ../common/istio-1-11/istio-crds/base
# - ../common/istio-1-11/istio-namespace/base
# - ../common/istio-1-11/istio-install/base
# OIDC Authservice
- ../common/oidc-authservice/base
# Dex
- ../common/dex/overlays/istio
# KNative
- ../common/knative/knative-serving/overlays/gateways
- ../common/knative/knative-eventing/base
- ../common/istio-1-11/cluster-local-gateway/base
# Kubeflow namespace
- ../common/kubeflow-namespace/base
# Kubeflow Roles
- ../common/kubeflow-roles/base
# Kubeflow Istio Resources
- ../common/istio-1-11/kubeflow-istio-resources/base


# Kubeflow Pipelines
- ../apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
# # KFServing
- ../apps/kfserving/upstream/overlays/kubeflow
# Katib
- ../apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- ../apps/centraldashboard/upstream/overlays/kserve
# Admission Webhook
- ../apps/admission-webhook/upstream/overlays/cert-manager
# Jupyter Web App
- ../apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Notebook Controller
- ../apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- ../apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- ../apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Controller
-  ../apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Web App
-  ../apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- ../apps/training-operator/upstream/overlays/kubeflow
# User namespace
- ../common/user-namespace/base

# KServe
- ../contrib/kserve/kserve
- ../contrib/kserve/models-web-app/overlays/kubeflow

images:
  - name: quay.io/jetstack/cert-manager-controller:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/jetstack.cert-manager-controller
    newTag: v1.5.0
  - name: quay.io/jetstack/cert-manager-cainjector:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/jetstack.cert-manager-cainjector
    newTag: v1.5.0
  - name: quay.io/jetstack/cert-manager-webhook:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/jetstack.cert-manager-webhook
    newTag: v1.5.0
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller@sha256:6ddffbc286a84048cfd090193d00b4ecda25a3a7bf2de1a8e873f8b3755cc913
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.controller
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook@sha256:9f70a2a8bb78781472fba0327c5d6ff91f13a29736d4502bf8ad3d60d3f16ccd
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.webhook
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_controller@sha256:904f42a768a9bc64999e7302d2bc7c1c48a08e74a82355cf57be513e6a124b82
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.channel_controller
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/in_memory/channel_dispatcher@sha256:a6983f71c04619928199cc21e07ee6f1e1c87586621bc03b10c9ba1abd92bfa8
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.channel_dispatcher
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/mtchannel_broker@sha256:a2678934d280ea19b0804cc7757d559a0312e2acea221b17a99bd830cd9eeaac
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.mtchannel_broker
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/broker/filter@sha256:0e25aa1613a3a1779b3f7b7f863e651e5f37520a7f6808ccad2164cc2b6a9b12
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.broker.filter
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/broker/ingress@sha256:cf579f88aa2a37c240e25bb886c1ef5404e326e12c7caf571e49308612243eee
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.broker.ingress
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping@sha256:edf462d03591e53e536640591a53538e6bea837fea15ed081eccfb42bc35a5c0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.eventing.cmd.mtping
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:fed92af8b9779c97482906db8857f27b5d4826708b75d0298aa30fad8900671f
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.serving.cmd.activator
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:bc5ae3090ab0322ed0e4f9efddb60fa85f6ff3a29156411d24d0e4764b18eba7
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.serving.cmd.autoscaler
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:bd7c6350e5d5c4edaa197a86fb96cff78bdd3e61f33fcb77aa60930de0ec0827
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.serving.cmd.controller
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook@sha256:1e371db6b1a9f9265fc7a55d15d98c935c0c28925ffde351fb3b93f331c5a08e
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.net-istio.cmd.webhook
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller@sha256:ff8680da52ef47b8573ebc3393cbfa2f0f14b05c1e02232807f22699adbef57a
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.net-istio.cmd.controller
    newTag: "20220624"
  - name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:6f41d379f1aacdfbb8f6d4f539e1769040e4f01bff3ad9c249b427e54dc56ea8
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.serving.cmd.webhook
    newTag: "20220624"
  - name: gcr.io/ml-pipeline/cache-server:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.cache-server
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/metadata-envoy:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.metadata-envoy
    newTag: "1.8.2"
  - name: gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/tfx-oss-public.ml_metadata_store_server
    newTag: "1.5.0"
  - name: gcr.io/ml-pipeline/metadata-writer:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.metadata-writer
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.minio
    newTag: RELEASE.2019-08-14T20-37-41Z-license-compliance
  - name: gcr.io/ml-pipeline/api-server:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.api-server
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/persistenceagent:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.persistenceagent
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/scheduledworkflow:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.scheduledworkflow
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/frontend:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.frontend
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/viewer-crd-controller:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.viewer-crd-controller
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/visualization-server:1.8.2
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.visualization-server
    newTag: "1.8.2"
  - name: gcr.io/ml-pipeline/mysql:5.7
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.mysql
    newTag: "5.7"
  - name: gcr.io/ml-pipeline/workflow-controller:v3.2.3-license-compliance
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/ml-pipeline.workflow-controller
    newTag: v3.2.3-license-compliance
  - name: gcr.io/arrikto/kubeflow/oidc-authservice:28c59ef
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/arrikto.kubeflow.oidc-authservice
    newTag: 28c59ef
  - name: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:0b8e031170354950f3395876961452af1c62f7ab5161c9e71867392c11881962
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/knative-releases.knative.dev.serving.cmd.queue
    newTag: "20220624"
  - name: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.notebook-controller
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.access-management
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.profile-controller
    newTag: v1.5.0
  - name: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/kubebuilder.kube-rbac-proxy
    newTag: v0.4.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.tensorboard-controller
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.tensorboards-web-app
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/training/training-operator:174e8813666951ded505daf334a37f60fd50c18d
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.training.training-operator
    newTag: 174e8813666951ded505daf334a37f60fd50c18d
  - name: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.volumes-web-app
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.admission-webhook
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.central-dashboard
    newTag: v1.5.0
  - name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.5.0
    newName: registry.cn-hangzhou.aliyuncs.com/seam-kubeflow/j1r0q0g6.notebooks.jupyter-web-app
    newTag: v1.5.0

