apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: mysql-pv
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim 
    namespace: kubeflow
  hostPath:
    path: /data/localvol/mysql
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
