apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: katib-mysql-pv
  name: katib-mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: katib-mysql
    namespace: kubeflow
  hostPath:
    path: /data/localvol/katib-mysql
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
