apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: minio-pv
  name: minio-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: minio-pvc
    namespace: kubeflow
  hostPath:
    path: /data/localvol/minio
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
